apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tenant-author-role
  labels:
    app.kubernetes.io/name: openbao-entity-operator
    app.kubernetes.io/managed-by: kustomize
rules:
- apiGroups:
  - openbao.openbao-operator.io
  resources:
  - openbaoauditdevices
  - openbaoauditrequestheaders
  - openbaoapproles
  - openbaoauthmethods
  - openbaocorsconfigurations
  - openbaoencryptionkeyconfigurations
  - openbaoentities
  - openbaoentityaliases
  - openbaogroupaliases
  - openbaogroups
  - openbaogroupmemberships
  - openbaokeyringrotationconfigurations
  - openbaonamespaces
  - openbaokubernetesauthroles
  - openbaologgers
  - openbaomfaloginenforcements
  - openbaomfamethods
  - openbaooidcassignments
  - openbaooidcclients
  - openbaooidcconfigs
  - openbaooidckeys
  - openbaooidcproviders
  - openbaooidcroles
  - openbaooidcscopes
  - openbaopasswordpolicies
  - openbaopersonas
  - openbaoplugins
  - openbaopolicies
  - openbaoratelimitquotas
  - openbaoratelimitquotaconfigurations
  - openbaosecretengines
  - openbaotokenroles
  - openbaouiheaders
  - openbaoworkflows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
