---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openbao.openbao-operator.io
  resources:
  - openbaoconnections
  - openbaoentities
  - openbaoentityaliases
  - openbaogroups
  - openbaopolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openbao.openbao-operator.io
  resources:
  - openbaoconnections/finalizers
  - openbaoentities/finalizers
  - openbaoentityaliases/finalizers
  - openbaogroups/finalizers
  - openbaopolicies/finalizers
  verbs:
  - update
- apiGroups:
  - openbao.openbao-operator.io
  resources:
  - openbaoconnections/status
  - openbaoentities/status
  - openbaoentityaliases/status
  - openbaogroupmemberships/status
  - openbaogroups/status
  - openbaopolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - openbao.openbao-operator.io
  resources:
  - openbaogroupmemberships
  verbs:
  - get
  - list
  - watch
