apiVersion: openbao.openbao-operator.io/v1alpha1
kind: OpenBaoConnection
metadata:
  labels:
    app.kubernetes.io/name: openbao-entity-operator
    app.kubernetes.io/managed-by: kustomize
  name: openbaoconnection-kubernetes-auth
spec:
  address: https://openbao.example.com:8200
  kubernetesAuth:
    mountPath: kubernetes
    role: openbao-entity-operator
