/*
Copyright 2026 openbao-entity-operator contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// OpenBaoTokenRoleSpec defines a role in OpenBao's built-in token auth method.
// +kubebuilder:validation:XValidation:rule="self.connectionRef == oldSelf.connectionRef",message="connectionRef is immutable; delete and recreate the OpenBaoTokenRole"
type OpenBaoTokenRoleSpec struct {
	// ConnectionRef selects the OpenBao API connection in the same namespace.
	ConnectionRef OpenBaoConnectionReference `json:"connectionRef"`

	// CreationPolicy controls how an external role is acquired.
	// +optional
	// +kubebuilder:default=Create
	// +kubebuilder:validation:Enum=Create;Adopt;CreateOrAdopt
	CreationPolicy CreationPolicy `json:"creationPolicy,omitempty"`

	// DeletionPolicy controls whether the external role is deleted with this resource.
	// +optional
	// +kubebuilder:default=Orphan
	// +kubebuilder:validation:Enum=Delete;Orphan
	DeletionPolicy DeletionPolicy `json:"deletionPolicy,omitempty"`

	// DriftDetectionInterval controls periodic checks for changes made outside Kubernetes.
	// A zero duration disables periodic checks. When omitted, the operator default is used.
	// +optional
	DriftDetectionInterval *metav1.Duration `json:"driftDetectionInterval,omitempty"`

	// AllowedEntityAliases limits entity aliases that may be attached to tokens from this role.
	// +listType=set
	// +optional
	AllowedEntityAliases []string `json:"allowedEntityAliases,omitempty"`

	// AllowedPolicies limits policies that callers may request for generated tokens.
	// +listType=set
	// +optional
	AllowedPolicies []string `json:"allowedPolicies,omitempty"`

	// AllowedPoliciesGlob limits policies using OpenBao glob patterns.
	// +listType=set
	// +optional
	AllowedPoliciesGlob []string `json:"allowedPoliciesGlob,omitempty"`

	// DisallowedPolicies rejects requested policies in this set.
	// +listType=set
	// +optional
	DisallowedPolicies []string `json:"disallowedPolicies,omitempty"`

	// DisallowedPoliciesGlob rejects requested policies matching these globs.
	// +listType=set
	// +optional
	DisallowedPoliciesGlob []string `json:"disallowedPoliciesGlob,omitempty"`

	// TokenBoundCIDRs restricts issued tokens to these client address ranges.
	// +listType=set
	// +optional
	TokenBoundCIDRs []string `json:"tokenBoundCIDRs,omitempty"`

	// TokenExplicitMaxTTL gives issued tokens an explicit maximum TTL.
	// +optional
	TokenExplicitMaxTTL *metav1.Duration `json:"tokenExplicitMaxTTL,omitempty"`

	// TokenPeriod gives issued tokens a fixed renewable period.
	// +optional
	TokenPeriod *metav1.Duration `json:"tokenPeriod,omitempty"`

	// TokenNumUses limits how many times an issued token may be used. Zero means unlimited.
	// +optional
	TokenNumUses *int64 `json:"tokenNumUses,omitempty"`

	// TokenNoDefaultPolicy prevents OpenBao from adding the default policy.
	// +optional
	TokenNoDefaultPolicy *bool `json:"tokenNoDefaultPolicy,omitempty"`

	// TokenType selects the type of token generated by the role.
	// +optional
	// +kubebuilder:validation:Enum=service;batch
	TokenType string `json:"tokenType,omitempty"`

	// Orphan controls whether generated tokens have no parent token.
	// +optional
	Orphan *bool `json:"orphan,omitempty"`

	// Renewable controls whether generated tokens can be renewed.
	// +optional
	Renewable *bool `json:"renewable,omitempty"`

	// PathSuffix adds a suffix to generated token paths for targeted revocation.
	// +optional
	PathSuffix string `json:"pathSuffix,omitempty"`
}

// OpenBaoTokenRoleStatus defines the observed state of an OpenBao token role.
type OpenBaoTokenRoleStatus struct {
	// Name is the OpenBao role name.
	// +optional
	Name string `json:"name,omitempty"`

	// ConfigHash is the SHA-256 hash of the normalized role configuration.
	// +optional
	ConfigHash string `json:"configHash,omitempty"`

	// ObservedGeneration is the most recent generation reflected in status.
	// +optional
	ObservedGeneration int64 `json:"observedGeneration,omitempty"`

	// Conditions represent the latest available observations of the role.
	// +listType=map
	// +listMapKey=type
	// +optional
	Conditions []metav1.Condition `json:"conditions,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:categories=openbao
// +kubebuilder:printcolumn:name="Config Hash",type=string,JSONPath=`.status.configHash`
// +kubebuilder:printcolumn:name="Ready",type=string,JSONPath=`.status.conditions[?(@.type=="Ready")].status`
// +kubebuilder:printcolumn:name="Reason",type=string,JSONPath=`.status.conditions[?(@.type=="Ready")].reason`
// +kubebuilder:printcolumn:name="Age",type=date,JSONPath=`.metadata.creationTimestamp`

// OpenBaoTokenRole is the Schema for the openbaotokenroles API.
type OpenBaoTokenRole struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitzero"`
	Spec              OpenBaoTokenRoleSpec   `json:"spec"`
	Status            OpenBaoTokenRoleStatus `json:"status,omitzero"`
}

// +kubebuilder:object:root=true

// OpenBaoTokenRoleList contains a list of OpenBaoTokenRole.
type OpenBaoTokenRoleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitzero"`
	Items           []OpenBaoTokenRole `json:"items"`
}

func init() {
	SchemeBuilder.Register(func(s *runtime.Scheme) error {
		s.AddKnownTypes(SchemeGroupVersion, &OpenBaoTokenRole{}, &OpenBaoTokenRoleList{})
		return nil
	})
}
