//go:build !ignore_autogenerated

/*
Copyright 2026 openbao-entity-operator contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesAuthSpec) DeepCopyInto(out *KubernetesAuthSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesAuthSpec.
func (in *KubernetesAuthSpec) DeepCopy() *KubernetesAuthSpec {
	if in == nil {
		return nil
	}
	out := new(KubernetesAuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenBaoConnection) DeepCopyInto(out *OpenBaoConnection) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenBaoConnection.
func (in *OpenBaoConnection) DeepCopy() *OpenBaoConnection {
	if in == nil {
		return nil
	}
	out := new(OpenBaoConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenBaoConnection) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenBaoConnectionList) DeepCopyInto(out *OpenBaoConnectionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenBaoConnection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenBaoConnectionList.
func (in *OpenBaoConnectionList) DeepCopy() *OpenBaoConnectionList {
	if in == nil {
		return nil
	}
	out := new(OpenBaoConnectionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenBaoConnectionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenBaoConnectionReference) DeepCopyInto(out *OpenBaoConnectionReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenBaoConnectionReference.
func (in *OpenBaoConnectionReference) DeepCopy() *OpenBaoConnectionReference {
	if in == nil {
		return nil
	}
	out := new(OpenBaoConnectionReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenBaoConnectionSpec) DeepCopyInto(out *OpenBaoConnectionSpec) {
	*out = *in
	if in.TokenSecretRef != nil {
		in, out := &in.TokenSecretRef, &out.TokenSecretRef
		*out = new(SecretKeyReference)
		**out = **in
	}
	if in.KubernetesAuth != nil {
		in, out := &in.KubernetesAuth, &out.KubernetesAuth
		*out = new(KubernetesAuthSpec)
		**out = **in
	}
	if in.CABundleSecretRef != nil {
		in, out := &in.CABundleSecretRef, &out.CABundleSecretRef
		*out = new(SecretKeyReference)
		**out = **in
	}
	if in.RequestTimeout != nil {
		in, out := &in.RequestTimeout, &out.RequestTimeout
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenBaoConnectionSpec.
func (in *OpenBaoConnectionSpec) DeepCopy() *OpenBaoConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(OpenBaoConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenBaoConnectionStatus) DeepCopyInto(out *OpenBaoConnectionStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenBaoConnectionStatus.
func (in *OpenBaoConnectionStatus) DeepCopy() *OpenBaoConnectionStatus {
	if in == nil {
		return nil
	}
	out := new(OpenBaoConnectionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenBaoEntity) DeepCopyInto(out *OpenBaoEntity) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenBaoEntity.
func (in *OpenBaoEntity) DeepCopy() *OpenBaoEntity {
	if in == nil {
		return nil
	}
	out := new(OpenBaoEntity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenBaoEntity) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenBaoEntityAlias) DeepCopyInto(out *OpenBaoEntityAlias) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenBaoEntityAlias.
func (in *OpenBaoEntityAlias) DeepCopy() *OpenBaoEntityAlias {
	if in == nil {
		return nil
	}
	out := new(OpenBaoEntityAlias)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenBaoEntityAlias) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenBaoEntityAliasList) DeepCopyInto(out *OpenBaoEntityAliasList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenBaoEntityAlias, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenBaoEntityAliasList.
func (in *OpenBaoEntityAliasList) DeepCopy() *OpenBaoEntityAliasList {
	if in == nil {
		return nil
	}
	out := new(OpenBaoEntityAliasList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenBaoEntityAliasList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenBaoEntityAliasSpec) DeepCopyInto(out *OpenBaoEntityAliasSpec) {
	*out = *in
	out.ConnectionRef = in.ConnectionRef
	out.EntityRef = in.EntityRef
	if in.DriftDetectionInterval != nil {
		in, out := &in.DriftDetectionInterval, &out.DriftDetectionInterval
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenBaoEntityAliasSpec.
func (in *OpenBaoEntityAliasSpec) DeepCopy() *OpenBaoEntityAliasSpec {
	if in == nil {
		return nil
	}
	out := new(OpenBaoEntityAliasSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenBaoEntityAliasStatus) DeepCopyInto(out *OpenBaoEntityAliasStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenBaoEntityAliasStatus.
func (in *OpenBaoEntityAliasStatus) DeepCopy() *OpenBaoEntityAliasStatus {
	if in == nil {
		return nil
	}
	out := new(OpenBaoEntityAliasStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenBaoEntityList) DeepCopyInto(out *OpenBaoEntityList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenBaoEntity, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenBaoEntityList.
func (in *OpenBaoEntityList) DeepCopy() *OpenBaoEntityList {
	if in == nil {
		return nil
	}
	out := new(OpenBaoEntityList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenBaoEntityList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenBaoEntityReference) DeepCopyInto(out *OpenBaoEntityReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenBaoEntityReference.
func (in *OpenBaoEntityReference) DeepCopy() *OpenBaoEntityReference {
	if in == nil {
		return nil
	}
	out := new(OpenBaoEntityReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenBaoEntitySpec) DeepCopyInto(out *OpenBaoEntitySpec) {
	*out = *in
	out.ConnectionRef = in.ConnectionRef
	if in.DriftDetectionInterval != nil {
		in, out := &in.DriftDetectionInterval, &out.DriftDetectionInterval
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Policies != nil {
		in, out := &in.Policies, &out.Policies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenBaoEntitySpec.
func (in *OpenBaoEntitySpec) DeepCopy() *OpenBaoEntitySpec {
	if in == nil {
		return nil
	}
	out := new(OpenBaoEntitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenBaoEntityStatus) DeepCopyInto(out *OpenBaoEntityStatus) {
	*out = *in
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Policies != nil {
		in, out := &in.Policies, &out.Policies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenBaoEntityStatus.
func (in *OpenBaoEntityStatus) DeepCopy() *OpenBaoEntityStatus {
	if in == nil {
		return nil
	}
	out := new(OpenBaoEntityStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenBaoGroup) DeepCopyInto(out *OpenBaoGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenBaoGroup.
func (in *OpenBaoGroup) DeepCopy() *OpenBaoGroup {
	if in == nil {
		return nil
	}
	out := new(OpenBaoGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenBaoGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenBaoGroupList) DeepCopyInto(out *OpenBaoGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenBaoGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenBaoGroupList.
func (in *OpenBaoGroupList) DeepCopy() *OpenBaoGroupList {
	if in == nil {
		return nil
	}
	out := new(OpenBaoGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenBaoGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenBaoGroupMembership) DeepCopyInto(out *OpenBaoGroupMembership) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenBaoGroupMembership.
func (in *OpenBaoGroupMembership) DeepCopy() *OpenBaoGroupMembership {
	if in == nil {
		return nil
	}
	out := new(OpenBaoGroupMembership)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenBaoGroupMembership) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenBaoGroupMembershipList) DeepCopyInto(out *OpenBaoGroupMembershipList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenBaoGroupMembership, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenBaoGroupMembershipList.
func (in *OpenBaoGroupMembershipList) DeepCopy() *OpenBaoGroupMembershipList {
	if in == nil {
		return nil
	}
	out := new(OpenBaoGroupMembershipList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenBaoGroupMembershipList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenBaoGroupMembershipSpec) DeepCopyInto(out *OpenBaoGroupMembershipSpec) {
	*out = *in
	out.GroupRef = in.GroupRef
	if in.EntityRef != nil {
		in, out := &in.EntityRef, &out.EntityRef
		*out = new(OpenBaoEntityReference)
		**out = **in
	}
	if in.MemberGroupRef != nil {
		in, out := &in.MemberGroupRef, &out.MemberGroupRef
		*out = new(OpenBaoGroupReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenBaoGroupMembershipSpec.
func (in *OpenBaoGroupMembershipSpec) DeepCopy() *OpenBaoGroupMembershipSpec {
	if in == nil {
		return nil
	}
	out := new(OpenBaoGroupMembershipSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenBaoGroupMembershipStatus) DeepCopyInto(out *OpenBaoGroupMembershipStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenBaoGroupMembershipStatus.
func (in *OpenBaoGroupMembershipStatus) DeepCopy() *OpenBaoGroupMembershipStatus {
	if in == nil {
		return nil
	}
	out := new(OpenBaoGroupMembershipStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenBaoGroupReference) DeepCopyInto(out *OpenBaoGroupReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenBaoGroupReference.
func (in *OpenBaoGroupReference) DeepCopy() *OpenBaoGroupReference {
	if in == nil {
		return nil
	}
	out := new(OpenBaoGroupReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenBaoGroupSpec) DeepCopyInto(out *OpenBaoGroupSpec) {
	*out = *in
	out.ConnectionRef = in.ConnectionRef
	if in.DriftDetectionInterval != nil {
		in, out := &in.DriftDetectionInterval, &out.DriftDetectionInterval
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Policies != nil {
		in, out := &in.Policies, &out.Policies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenBaoGroupSpec.
func (in *OpenBaoGroupSpec) DeepCopy() *OpenBaoGroupSpec {
	if in == nil {
		return nil
	}
	out := new(OpenBaoGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenBaoGroupStatus) DeepCopyInto(out *OpenBaoGroupStatus) {
	*out = *in
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Policies != nil {
		in, out := &in.Policies, &out.Policies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MemberEntityIDs != nil {
		in, out := &in.MemberEntityIDs, &out.MemberEntityIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MemberGroupIDs != nil {
		in, out := &in.MemberGroupIDs, &out.MemberGroupIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ManagedMemberEntityIDs != nil {
		in, out := &in.ManagedMemberEntityIDs, &out.ManagedMemberEntityIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ManagedMemberGroupIDs != nil {
		in, out := &in.ManagedMemberGroupIDs, &out.ManagedMemberGroupIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenBaoGroupStatus.
func (in *OpenBaoGroupStatus) DeepCopy() *OpenBaoGroupStatus {
	if in == nil {
		return nil
	}
	out := new(OpenBaoGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyReference) DeepCopyInto(out *SecretKeyReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyReference.
func (in *SecretKeyReference) DeepCopy() *SecretKeyReference {
	if in == nil {
		return nil
	}
	out := new(SecretKeyReference)
	in.DeepCopyInto(out)
	return out
}
