{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "openbao-entity-operator.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "openbao-entity-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
spec:
  ports:
    - name: {{ ternary "https" "http" .Values.metrics.secure }}
      port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "openbao-entity-operator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: controller
{{- end }}
