{{- if and .Values.metrics.enabled .Values.metrics.secure }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "openbao-entity-operator.fullname" . }}-metrics-auth
  labels:
{{ include "openbao-entity-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "openbao-entity-operator.fullname" . }}-metrics-auth
subjects:
  - kind: ServiceAccount
    name: {{ include "openbao-entity-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
